### ISSUE TITLE
[Feature Request] - JSON Beautifier in WebSockets history

### ISSUE THREAD

**Issue by AlexandreGohier** [NetSPI/JSONBeautifier#4]
![screen shot 2018-03-03 at 14 51 56](https://user-images.githubusercontent.com/37018962/36935067-a3793896-1ef2-11e8-9636-35d1ae7045f1.png)

Would it be possible to get the "JSON Beautifier" tab in the "WebSockets history" proxy section as well when web socket messages contain JSON?

Thanks a lot for you work.

**Comment by JacobReynolds** [comment]
Hey William,

Great suggestion, I think that could be useful too. Looking into it, it looks like Burp doesn't currently provide Extender support for WebSockets. https://support.portswigger.net/customer/portal/questions/16829255-websockets-api-support

If that ever does come available though I'll definitely add this.  Closing for now though.

**Comment by AlexandreGohier** [comment]
Alright thanks!
